require:
  - rubocop-rspec

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: false
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: false
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: false
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: false
Lint/EmptyBlock: # (new in 1.1)
  Enabled: false
Lint/EmptyClass: # (new in 1.3)
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: false
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: false
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: false
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: false
Lint/SymbolConversion: # (new in 1.9)
  Enabled: false
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: false
Lint/TripleQuotes: # (new in 1.9)
  Enabled: false
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: false
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: false
Style/CollectionCompact: # (new in 1.2)
  Enabled: false
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: false
Style/EndlessMethod: # (new in 1.8)
  Enabled: false
Style/HashExcept: # (new in 1.7)
  Enabled: false
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: false
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: false
Style/NilLambda: # (new in 1.3)
  Enabled: false
Style/RedundantArgument: # (new in 1.4)
  Enabled: false
Style/SwapValues: # (new in 1.1)
  Enabled: false
